# Read build script documentation https://docs.armbian.com/Developer-Guide_Build-Options/
# for detailed explanation of these options and for additional options not listed here

export BOARD="maixsense" 
export BRANCH="edge" 
export BUILD_MINIMAL="yes" 
export KERNEL_BTF="no" 
export KERNEL_CONFIGURE="no" 
export RELEASE="bookworm"
